#!url=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/Adguard.module
#!name=AdGuard 解锁永久高级版
#!desc=AdGuard 解锁永久高级版
#更新时间:2023-01-29


[Script]
AdGuard 解锁永久高级版 = type=http-response,pattern=^https?:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt,requires-body=1,max-size=0,script-path=https://github.com/itcast-l/shadowrocket-module/raw/main/js/Adguard.js

[MITM]
hostname= %APPEND% *.adguard.org
