#!name=B站高清解锁
#!desc=B站高清解锁
#脚本作者:Luyc
#更新时间:2023-01-29
#使用声明：️仅供学习交流，🈲️商业用途

[Script]
B站高清解锁 = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\?,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
[MITM]
hostname= %APPEND% app.bilibili.com,api.live.bilibili.com,api.vc.bilibili.com, api.bilibili.com, manga.bilibili.com, grpc.biliapi.net,api.biliapi.net, -broadcast.chat.bilibili.com, -*cdn*.biliapi.net, -*tracker*.biliapi.net
