#url=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/keep.module
#!name=keep
#!desc=keep
#软件版本:7.44.1
#脚本作者:King
#更新时间:2023.2.14
#使用声明：️此脚本仅供学习与交流，

[Script]
keep = type=http-response,pattern=^https://api.gotokeep.com.+,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/js/keep.js

[MITM]
hostname= %APPEND% api.gotokeep.com
