#url=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/NetEase.module
#!name=网易云音乐vip
#!desc=网易云音乐vip
#软件版本:所有
#脚本作者:伟人
#更新时间:2022-11-23
#使用声明：️此脚本仅供学习与交流，请勿转载与贩卖！️
[Script]
网易云音乐vip = type=http-request,pattern=^http[s]?:\/\/.+music.+(player\/url|playlist|entrance|\/eapi\/search\/).*$,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/js/NetEase.js

[MITM]
hostname= %APPEND% *.music.163.com
