#url=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/Nicegram.module
#!name=Nicegram会员
#!desc=Nicegram会员
#更新时间：2023-02-08

[Script]
Nicegram会员=type=http-request,pattern=^https?:\/\/restore-access\.indream\.app\/restoreAccess\?id=\w+$,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/js/Nicegram.js,script-update-interval=0
[MITM]
hostname= %APPEND% restore-access.indream.app

