#!url=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/SpotifyFY.module
#!name=Spotify歌词翻译
#!desc=Spotify歌词翻译
#脚本功能:解锁专业版，滑动截屏
#更新时间:2023-01-29
#使用声明：️仅供学习交流，🈲️商业用途

[Script]
# 修改下方argument中的appid和securityKey,填入自己的appid和密钥
spotify歌词翻译 = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/color-lyrics\/v2\/track\/,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://github.com/itcast-l/shadowrocket-module/raw/main/js/SpotifyFY.js,argument=appid=123&securityKey=321
