#!url=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/Tiktok.module
#!name=Tiktok免拔卡观看
#!desc=Tiktok免拔卡观看,支持版本 Tiktok 21.1.0,安装包查看群内置顶
#Tg：https://t.me/it_cast
#更新时间:2023-01-30
#使用声明：️JP 为日本，可修改其他地区

[URL Rewrite]
(?<=_region=)CN(?=&) JP 307
(?<=&mcc_mnc=)4 2 307
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302

[MITM]
hostname = %APPEND% *.tiktokv.com,*.byteoversea.com,*.tik-tokapi.com
