#!name=知乎 盐故事+知识+书刊+去部分广告
#!desc=知乎 盐故事+知识+书刊+去部分广告
#软件版本:所有
#更新时间:2023-02-19

[Script]
知乎 盐故事+知识+书刊+去部分广告
直免费下去。还希望支持我。 = type=http-response,pattern=^http[s]?:\/\/api\.zhihu\.com\/(people\/self|unlimited\/go\/my_card|sku\/reversion_sku_ext).*$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/js/zhihu7.js
知乎 盐故事+知识+书刊+去部分广告
直免费下去。还希望支持我。 = type=http-request,pattern=^http[s]?:\/\/.*zhihu\.(com|cn)\/(appview\/v2\/answer|remix-web\/paid_columns|km_player\/album|market\/paid_column|appview\/p|api\/v3\/books|books|market\/paid_magazine).*$,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/itcast-l/shadowrocket-module/main/js/shukan2.js

[MITM]
hostname= %APPEND% *1*1*,125.77.176*,27.148*,183.204*,122.224*,60.188.72*,120.220*,120.222*,103.41.167.236,150.109.91*,*.zhihu.*
